project:
  type: website
  output-dir: .
  resources:
    - projects/job-market-analysis-2024/references.bib

website:
  title: "jimmm123"
  navbar:
    left:
      - text: About Me
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    css: style.css
    theme: cosmo
    toc: false
execute:
  echo: false
  eval: true
  code-fold: true
  warning: false
  message: false
